
package cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculadoraImplementacionService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/WS/Calculadora?wsdl")
public class CalculadoraImplementacionService
    extends Service
{

    private final static URL CALCULADORAIMPLEMENTACIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULADORAIMPLEMENTACIONSERVICE_EXCEPTION;
    private final static QName CALCULADORAIMPLEMENTACIONSERVICE_QNAME = new QName("http://ws/", "CalculadoraImplementacionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/Calculadora?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULADORAIMPLEMENTACIONSERVICE_WSDL_LOCATION = url;
        CALCULADORAIMPLEMENTACIONSERVICE_EXCEPTION = e;
    }

    public CalculadoraImplementacionService() {
        super(__getWsdlLocation(), CALCULADORAIMPLEMENTACIONSERVICE_QNAME);
    }

    public CalculadoraImplementacionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULADORAIMPLEMENTACIONSERVICE_QNAME, features);
    }

    public CalculadoraImplementacionService(URL wsdlLocation) {
        super(wsdlLocation, CALCULADORAIMPLEMENTACIONSERVICE_QNAME);
    }

    public CalculadoraImplementacionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULADORAIMPLEMENTACIONSERVICE_QNAME, features);
    }

    public CalculadoraImplementacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraImplementacionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "CalculadoraImplementacionPort")
    public Calculadora getCalculadoraImplementacionPort() {
        return super.getPort(new QName("http://ws/", "CalculadoraImplementacionPort"), Calculadora.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "CalculadoraImplementacionPort")
    public Calculadora getCalculadoraImplementacionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "CalculadoraImplementacionPort"), Calculadora.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULADORAIMPLEMENTACIONSERVICE_EXCEPTION!= null) {
            throw CALCULADORAIMPLEMENTACIONSERVICE_EXCEPTION;
        }
        return CALCULADORAIMPLEMENTACIONSERVICE_WSDL_LOCATION;
    }

}
